# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default

bases:
- keycloak

resources:
- bases/deploy.delv.com_matedeploys.yaml
# +kubebuilder:scaffold:crdkustomizeresource