apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subscription-admin
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - "operators.coreos.com"
    resources:
      - subscriptions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
